name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Tag Docker image
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app
        run: |
          docker tag my-python-app:latest $ECR_REPOSITORY:latest

      - name: Push Docker image to Amazon ECR
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app
        run: |
          docker push $ECR_REPOSITORY:latest
