name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Tag Docker image
        run: docker tag my-python-app:latest 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 885626464789.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
